/** Token usage information */
export type Usage = {
  prompt_tokens: number;
  completion_tokens: number;
  total_tokens: number;
};

/** A chunk of agent output (streaming or stored) */
export type AgentChunk = {
  type:
    | "user"
    | "ask"
    | "thinking"
    | "tool_call"
    | "tool_call_args"
    | "tool_result"
    | "tool_call_pending"
    | "say"
    | "attempt_completion"
    | "assistant"
    | "completion"
    | "usage"
    | "tool_job_started"
    | "artifact";
  id: string;
  text?: string;
  created_at: string;
  user_id?: string;
  thinking?: string;
  tool_name?: string;
  tool_arguments?: string;
  tool_result?: string;
  tool_id?: string;
  args?: Record<string, unknown>;
  fire_and_forget?: boolean;
  content?: string;
  result?: string;
  is_finished?: boolean;
  isStreaming?: boolean;
  options?: string[];
  // usage fields
  prompt_tokens?: number;
  completion_tokens?: number;
  total_tokens?: number;
  total_cost?: number;
  // tool_job_started fields
  job_id?: string;
  provider?: string;
  // vision: image preview data URLs attached to user messages
  imageUrls?: string[];
  // artifact fields
  artifact_id?: string;
  content_type?: string;
  filename?: string;
  url?: string;
  size_bytes?: number;
  metadata?: Record<string, unknown>;
};

/** Inline attachment sent as base64 with the agent request */
export type InlineAttachment = {
  filename: string;
  content_type: string;
  data: string; // base64-encoded
};

/** Request payload for executing an agent task */
export type AgentExecuteRequest = {
  task: string;
  model?: string;
  max_requests?: number;
  tool_access?: ToolAccess;
  use_json_tool_calls?: boolean;
  client_tools?: ClientToolDefinition[];
  attachments?: InlineAttachment[];
};

/** Tool access permissions for agent execution */
export type ToolAccess = {
  filesystem?: boolean;
  command?: boolean;
  coding_agent_job?: boolean;
  web_search?: boolean;
  url_fetch?: boolean;
  sub_agent?: boolean;
};

/** Information about a single LLM model */
export type ModelInfo = {
  id: string;
  name: string;
  provider: string;
  supported_features: string[];
  description?: string | null;
  context_window?: number | null;
  max_output_tokens?: number | null;
};

/** A session summary */
export type SessionSummary = {
  id: string;
  name: string;
  created_at: string;
};

/** Auth config */
export type AuthConfig = {
  apiBaseUrl: string;
  accessToken: string;
  tenantId: string;
  userId?: string;
};

/** File attachment for upload */
export type FileAttachment = {
  id: string;
  name: string;
  size: number;
  type: string;
  data?: Uint8Array;
  url?: string;
  preview?: string; // base64 data URL for image thumbnails
  isVision?: boolean; // true if the file is a vision-capable image
};

/** A single version snapshot of an artifact */
export type ArtifactVersion = {
  version: number;
  content: string;
  createdAt: string;
};

/** Artifact generated by the assistant */
export type Artifact = {
  id: string;
  type:
    | "code"
    | "excel"
    | "pptx"
    | "pdf"
    | "image"
    | "markdown"
    | "mermaid"
    | "csv"
    | "html"
    | "jsx"
    | "docx";
  title: string;
  content: string;
  language?: string;
  url?: string;
  createdAt: string;
  /** Version history (latest first) */
  versions?: ArtifactVersion[];
  /** Current version number (1-based) */
  currentVersion?: number;
  /** Workspace metadata for sandbox-generated files */
  workspace?: {
    workspaceId: string;
    filename: string;
  };
};

// Excel types
export type ExcelData = { sheets: SheetData[] };
export type SheetData = {
  name: string;
  rows: CellValue[][];
  row_count: number;
  col_count: number;
};
export type CellValue =
  | { type: "Empty" }
  | { type: "String"; value: string }
  | { type: "Number"; value: number }
  | { type: "Bool"; value: boolean }
  | { type: "Error"; value: string };
export type WriteExcelRequest = { sheets: WriteSheetData[] };
export type WriteSheetData = {
  name: string;
  headers?: string[];
  rows: unknown[][];
  column_widths?: number[];
};

// PPTX types
export type PptxMetadata = {
  slide_count: number;
  title?: string;
  slides: SlideInfo[];
};
export type SlideInfo = {
  index: number;
  title?: string;
  text_content: string;
};

// Tool execution types
export type ToolCall = {
  name: string;
  arguments: Record<string, unknown>;
};
export type ToolResult = {
  tool_id: string;
  result: unknown;
  error?: string;
};

// PDF types
export type PdfData = {
  page_count: number;
  pages: PdfPageData[];
  metadata: PdfMetadata;
};
export type PdfPageData = {
  page_number: number;
  text: string;
};
export type PdfMetadata = {
  title?: string;
  author?: string;
  subject?: string;
  creator?: string;
};

// DOCX types
export type DocxData = {
  paragraphs: DocxParagraph[];
  tables: DocxTable[];
  metadata: DocxMetadataInfo;
};
export type DocxParagraph = {
  text: string;
  style?: string;
};
export type DocxTable = {
  rows: string[][];
};
export type DocxMetadataInfo = {
  title?: string;
  author?: string;
  description?: string;
};

// Sandbox execution types
export type ExecuteCodeRequest = {
  language: string;
  code: string;
  timeout_secs?: number;
};
export type ExecuteCodeResult = {
  stdout: string;
  stderr: string;
  exit_code: number;
  timed_out: boolean;
  duration_ms: number;
  workspace_id: string;
  workspace_files: WorkspaceFile[];
};
export type GenerateFileRequest = {
  file_type: string;
  data: Record<string, unknown>;
  output_path?: string;
};
export type GenerateFileResult = {
  file_bytes: number[];
  file_name: string;
  saved_path?: string;
  workspace_id: string;
  workspace_files: WorkspaceFile[];
};
export type WorkspaceFile = {
  name: string;
  path: string;
  size: number;
  is_dir: boolean;
};

export type ClientToolDefinition = {
  name: string;
  description: string;
  parameters?: Record<string, unknown>;
  fire_and_forget?: boolean;
};
